### ISSUE TITLE
FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by alouanemed** [tbruyelle/RxPermissions#214] opened 2018-03-12 22:40 UTC
```
Caused by: java.lang.IllegalStateException: FragmentManager is already executing transactions
                                                                                     at android.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:1981)
                                                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2037)
                                                                                     at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:799)
                                                                                     at com.tbruyelle.rxpermissions2.RxPermissions.getRxPermissionsFragment(RxPermissions.java:54)
                                                                                     at com.tbruyelle.rxpermissions2.RxPermissions.<init>(RxPermissions.java:41)
                                                                                     at com......MessagesActivity.initViews(MessagesActivity.java:113)
```

in this code : 

`    rxPermissions = new RxPermissions(this);
`

I don't know exactly the reason behind this as it was working before without any issue.

**Comment by rogerou** [comment] 2018-06-06 03:16
same

**Comment by epool** [comment] 2018-07-06 19:33
this should be fixed with #233

**Comment by leodeleon22** [comment] 2018-07-10 08:37
I'm targeting API 27 and I also have this  error if I request the permission onViewCreated on a Fragment. What's the workaround?

**Comment by chetbox** [comment] 2018-07-10 08:58
I have the same issue as @leodeleon22 using version 0.10.1.

Stack trace:

```
    java.lang.IllegalStateException: FragmentManager is already executing transactions
        at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2179)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2211)
        at android.support.v4.app.BackStackRecord.commitNow(BackStackRecord.java:643)
        at com.tbruyelle.rxpermissions2.RxPermissions.getRxPermissionsFragment(RxPermissions.java:71)
        at com.tbruyelle.rxpermissions2.RxPermissions.access$000(RxPermissions.java:34)
        at com.tbruyelle.rxpermissions2.RxPermissions$1.get(RxPermissions.java:54)
        at com.tbruyelle.rxpermissions2.RxPermissions$1.get(RxPermissions.java:47)
        at com.tbruyelle.rxpermissions2.RxPermissions.pending(RxPermissions.java:205)
        at com.tbruyelle.rxpermissions2.RxPermissions.request(RxPermissions.java:194)
        at com.tbruyelle.rxpermissions2.RxPermissions.access$100(RxPermissions.java:34)
        at com.tbruyelle.rxpermissions2.RxPermissions$2.apply(RxPermissions.java:96)
        at io.reactivex.Observable.compose(Observable.java:6284)
        at com.tbruyelle.rxpermissions2.RxPermissions.request(RxPermissions.java:170)
        at foo.MyFragment.onCreateView(MyFragment.kt:55)
        ...
```

 I tried moving the initialisation to `onStart` but that gives same error.

**Closed** 2018-07-10 21:14 UTC

**Comment by epool** [comment] 2018-07-10 21:24
@leodeleon22 @chetbox now when you instantiate `new RxPermissions(this)` from a fragment you have to pass the fragment instance instead of the fragment's activity. This is fixed with `v0.10.2`

**Comment by guness** [comment] 2018-12-08 12:56
> @leodeleon22 @chetbox now when you instantiate `new RxPermissions(this)` from a fragment you have to pass the fragment instance instead of the fragment's activity. This is fixed with `v0.10.2`

mate this is bug itself. not the fix.

**Comment by kirilamenski** [comment] 2019-02-21 12:20
Has anyone found solution?

**Comment by ronjdaugherty34** [comment] 2019-04-04 19:50
The dirty hack works I just added a second debounce to the chain 

rxPermissions.requestEachCombined(
            Manifest.permission.ACCESS_COARSE_LOCATION,
            Manifest.permission.CALL_PHONE, Manifest.permission.BLUETOOTH
        )
            .debounce(1, TimeUnit.SECONDS)

            .subscribe { permission ->

                when {
                    permission.granted -> toast("Can do ${permission.name}")
                    permission.shouldShowRequestPermissionRationale -> {
                        // Denied permission without ask never again

                    }
                    else -> {
                        // Denied permission with ask never again
                        // Need to go to the settings
                    }
                }
            }

**Comment by moz1q1** [comment] 2020-01-16 02:34
hi kid

**Comment by GensaGames** [comment] 2020-01-20 19:38
Any ideas, when this bug will be fixed? This is ridicules. You have inside method RxPermission, with could accept Activity, or Fragment. But for Activity it's crashing.

**Comment by mrArtCore** [comment] 2020-01-20 20:07
@GensaGames This is not ridiculous. It's been a long time since a saw the maintainer active in this repository. 
Maybe because of such commentators? The community of this repository does nothing just create issues. And if this is the cause of why maintainer is inactive so long I can't blame him. I understand.

But!
Why don't you fix this? Go and create PR, you are welcome!

**Comment by GensaGames** [comment] 2020-01-20 20:47
@mrArtCore  I'm sorry for my message tone above.

**Comment by mrArtCore** [comment] 2020-01-20 21:52
@GensaGames 
Nice to see your message above! Thanks! Take care !
And how about to fix it ? =))

**Comment by relaxedSoul** [comment] 2021-08-13 10:32
> Any ideas, when this bug will be fixed? This is ridicules. You have inside method RxPermission, with could accept Activity, or Fragment. But for Activity it's crashing.

To be honest, I am not sure there is actually a fix. It is the same as calling Activity.startActivityForResult inside Fragment and wait for result in Fragment.onActivityResult.

I mean, the only solution I see is creating annotations to say IDE to count it as a warning with the message. 

Just use the right methods in the right places. For me, the fix is made and I use the right constructor in the right place.
