### ISSUE TITLE
java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.

### ISSUE THREAD

**Issue by tarasantoshchuk** [tbruyelle/RxPermissions#46] opened 2016-05-10 15:05 UTC
One of my activities asks for camera permission on trigger (button click)
After following steps, exception is thrown:
1. user presses button and shadow activity with dialog that asks for permission is shown
2. user goes to settings and revoke some other permission
3. user reopens app - shadow activity with dialog is still there
4. user allows/denies permission and app crashes with exception

from what I saw in code:
RxPermissions.request_() where _mSubjects_ is filled is called before permission is revoked by user

After user revoked permission app is recreated in **new process** and _mSubjects_ is empty - therefore exception is thrown in RxPermissions.onRequestPermissionsResult()

Can you please fix this or suggest a workaround?

**Comment by tbruyelle** [comment] 2016-05-10 15:32
Do you answer the permission dialog on 1. ?

**Comment by tarasantoshchuk** [comment] 2016-05-10 15:42
no, I leave app while dialog is shown

**Comment by tbruyelle** [comment] 2016-05-10 15:50
Ok there's probably a bug but the case you described is kindy weird... Why the user would go to the settings *before* answering the permission dialog ?

**Comment by tarasantoshchuk** [comment] 2016-05-10 16:04
Yes, it is weird.
But our crash reporter shows that this crash happens in production

**Comment by tbruyelle** [comment] 2016-05-11 07:23
Can you provide a detailled stack trace please?

**Comment by tarasantoshchuk** [comment] 2016-05-11 08:17
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {.../com.tbruyelle.rxpermissions.ShadowActivity}: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
at android.app.ActivityThread.-wrap16(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
at com.tbruyelle.rxpermissions.RxPermissions.onRequestPermissionsResult(RxPermissions.java:286)
at com.tbruyelle.rxpermissions.ShadowActivity.onRequestPermissionsResult(ShadowActivity.java:32)
at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6582)
at android.app.Activity.dispatchActivityResult(Activity.java:6460)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742) 
at android.app.ActivityThread.-wrap16(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:148) 
at android.app.ActivityThread.main(ActivityThread.java:5417) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by tbruyelle** [comment] 2016-05-11 13:25
Ok I think I understand. 
When you update the app's permissions in the settings, your app is killed, and in that case RxPermissions doesn't save the current state, but the framework save the permission request and so restore it when the user is back.

RxPermissions should probably save the state when the app is killed, and restore it after. If you have some time to develop a fix, I could merge it. I don't have the time for the moment sorry.

**Comment by tarasantoshchuk** [comment] 2016-05-13 17:01
@tbruyelle 
please, review my pull request

**Comment by tarasantoshchuk** [comment] 2016-05-28 13:46
@tbruyelle 
I added new pull request that fixes crash, please review

**Comment by tushar-acharya** [comment] 2016-08-02 07:21
+1 Got the same issue in production.

**Comment by Dwite** [comment] 2016-08-04 13:43
@tbruyelle so what do you think about PR?

**Comment by AAverin** [comment] 2016-09-18 09:24
I have just started open beta for my app, have some 500 users, maybe half of them active at best.
Got 1 instance of this exception already. The only permission I ask for is Location

**Comment by tbruyelle** [comment] 2016-09-18 11:52
@AAverin Note that the bug affects only devices with sdk >= 23

**Comment by AAverin** [comment] 2016-09-18 11:54
@tbruyelle yes, you're right, my bug is on 6.0.1.
Well, that's a bit more reassuring, but probably should be resolved nevertheless

**Comment by tbruyelle** [comment] 2016-09-19 09:29
@AAverin Agree I want to resolve it but until now nobody found an acceptable fix.

**Comment by flztsj** [comment] 2016-09-19 09:31
I don't think the issue can be resolved.

**Comment by gotev** [comment] 2016-09-29 09:07
@flztsj if you request permissions without rx, even if you try the described steps, your app will not crash. I request permissions with this helper I wrote and it works: https://gist.github.com/gotev/67c300c563bdf68a502c

Maybe it can be useful to figure out what is going wrong with RxPermissions

**Comment by tbruyelle** [comment] 2016-10-20 18:21
Fixed in 0.8.0

**Closed** 2016-10-20 18:20 UTC
Labels: bug

**Comment by AAverin** [comment] 2016-11-05 09:34
@tbruyelle 0.8.0 is tag on github, but not marked as latest release. Is it safe to grab it and use?

**Comment by YellFunGit** [comment] 2016-11-29 09:07
I found that app will crash while mutil RxPermission request at one time. @tbruyelle caused by the same issue.

**Comment by epool** [comment] 2016-11-29 15:55
@YellFunGit what version are you using?
