### ISSUE TITLE
is it a bug？

### ISSUE THREAD

**Issue by daimaXZ** [tbruyelle/RxPermissions#82] opened 2016-10-08 09:00 UTC
RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request

**Comment by tbruyelle** [comment] 2016-10-15 17:10
Possible duplicate of #46

**Comment by tbruyelle** [comment] 2016-10-20 18:20
#46  is now fixed, please try again with version 0.8.0

**Closed by tbruyelle** 2016-10-20 18:20 UTC
