### ISSUE TITLE
Replacing fragment in subscription without commitAllowingStateLoss causing java.lang.RuntimeException: Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by ar-g** [tbruyelle/RxPermissions#132] opened 2017-03-30 06:10 UTC
Replacing fragment in subscription without commitAllowingStateLoss causing java.lang.RuntimeException: Failure delivering result ResultInfo.

This code will crash if called inside another fragment
```java
new RxPermissions(getActivity())
      .request(Manifest.permission.WRITE_EXTERNAL_STORAGE)
      .filter(RxUtil::isTrue)
      .subscribe(__ ->{
FragmentManager fragmentManager = activity.getSupportFragmentManager();
    fragmentManager.beginTransaction()
        .replace(containerId, fragment, fragment.getClass().getName())
        .commit();
}
      );
```

**Comment by mrArtCore** [comment] 2017-03-30 13:37
First of all, If it really cause crash, give verbose stackTrace here, please.

I can only imagine that you do so inside other fragment. 
And if the problem is only in "commitAllowingStateLoss" why don't you change your "commit" method to "commitAllowingStateLoss" in your chain ???

IMHO, if you don't mind, this is NOT library problem, only yours. Library work was done in the right way, and problems, that goes in "subscribe(...)"  only yours.

**Comment by ar-g** [comment] 2017-03-31 07:21
@mrArtCore it works with `commitAllowingStateLoss` but not with commit. 

Yes, I'm using nested fragments and `getChildFragmentManager` doesn't help. 

Well, this code works just fine without requesting permissions via this library

Here is stacktrace
`java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:android:fragment:0, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.lalafo/classifieds.yalla.features.ad.postingv2.PostingActivity}: rx.exceptions.OnErrorNotImplementedException: Can not perform this action after onSaveInstanceState
                                                              at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
                                                              at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
                                                              at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:148)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                           Caused by: rx.exceptions.OnErrorNotImplementedException: Can not perform this action after onSaveInstanceState
                                                              at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
                                                              at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
                                                              at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                              at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
                                                              at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                              at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216)
                                                              at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                              at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
                                                              at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511)
                                                              at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466)
                                                              at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244)
                                                              at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
                                                              at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                                                              at rx.internal.operators.OperatorBufferWithSize$BufferExact.onNext(OperatorBufferWithSize.java:114)
                                                              at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
                                                              at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
                                                              at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
                                                              at rx.observers.SerializedObserver.onNext(SerializedObserver.java:91)
                                                              at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94)
                                                              at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerNext(OnSubscribeConcatMap.java:182)
                                                              at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onNext(OnSubscribeConcatMap.java:335)
                                                              at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
                                                              at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
                                                              at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
                                                              at com.tbruyelle.rxpermissions.RxPermissionsFragment.onRequestPermissionsResult(RxPermissionsFragment.java:66)
                                                              at com.tbruyelle.rxpermissions.RxPermissionsFragment.onRequestPermissionsResult(RxPermissionsFragment.java:51)
                                                              at android.app.Activity.dispatchRequestPermissionsResultToFragment(Activity.java:6563)
                                                              at android.app.Activity.dispatchActivityResult(Activity.java:6436)
                                                              at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
                                                              at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742) 
                                                              at android.app.ActivityThread.-wrap16(ActivityThread.java) 
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                              at android.os.Looper.loop(Looper.java:148) 
                                                              at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                           Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                              at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
                                                              at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
                                                          	at android.support.v4.app.BackStackRecord.commitInternal(BackSta`

**Comment by mrArtCore** [comment] 2017-03-31 11:09
@ar-g I just miss something =)) if it works fine with `commitAllowingStateLoss` why don't you just use it ? ))
And your stacktrace clearly defined cause of crash 
...
`Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState`
I still can't get it, why did you open this issue ???

So, I want to give you advise. If You have some problem, crash or whatever, try to, maybe google it first and do not create issues on any repository so far, as you really sure, that this problem caused by library code. Not cooll at all !

@tbruyelle maybe you should close this issue now =) ?

**Comment by tbruyelle** [comment] 2017-03-31 11:47
Thank you for the replies, I close the issue

**Closed by tbruyelle** 2017-03-31 11:47 UTC

**Comment by ar-g** [comment] 2017-03-31 16:25
@mrArtCore 
My point is that library creates a scenario when the normal code doesn't work. Mb you can point out in docs that library use fragment inside and we should account for all issues related to it, i.e. it might not work ok when replacing nested fragment.

**Comment by mrArtCore** [comment] 2017-04-01 09:08
@ar-g 
Conception of **_normal code_** may vary for different persons. And as developer you are not beign forced to use any library or something. And you don't have to have nested fragments and request permissions inside one of them. Who told you that is **_normal_** to do like you did ? =))
All scenarious are created by developer, and developer define where exactly he want library do work for him/her. He/She define own "architecture", code structure and so on. Every of us get in troubles because of lacking knowleges, time, because of our laziness etc. 

Please, try to understand different between opening issue on lib repository and asking question on 
StackOverflow. Its not shameful to misknow something. 

Have a good coding! 
Cheers!

**Comment by imxy** [comment] 2019-04-08 03:46
`android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2080)
--
2 android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2219)
3 android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2239)
4 android.support.v4.app.BackStackRecord.commitNow(BackStackRecord.java:648)
5 com.tbruyelle.rxpermissions2.RxPermissions.com.tbruyelle.rxpermissions2.RxPermissionsFragment getRxPermissionsFragment(android.support.v4.app.FragmentManager)(RxPermissions.java:77)
6 com.tbruyelle.rxpermissions2.RxPermissions.com.tbruyelle.rxpermissions2.RxPermissionsFragment access$000(com.tbruyelle.rxpermissions2.RxPermissions,android.support.v4.app.FragmentManager)(RxPermissions.java:36)
7 ##_parent_##2##_parent_##
8 ##_child_## io.reactivex.Observable access$100(com.tbruyelle.rxpermissions2.RxPermissions,io.reactivex.Observable,java.lang.String[])##_child_##
9 ##_child_## io.reactivex.Observable access$200(com.tbruyelle.rxpermissions2.RxPermissions,java.lang.String[])##_child_##
10 com.tbruyelle.rxpermissions2.RxPermissions$1.com.tbruyelle.rxpermissions2.RxPermissionsFragment get()(RxPermissions.java:61)
11 com.tbruyelle.rxpermissions2.RxPermissions$1.java.lang.Object get()(RxPermissions.java:54)
12 com.tbruyelle.rxpermissions2.RxPermissions.io.reactivex.Observable pending(java.lang.String[])(RxPermissions.java:211)
13 com.tbruyelle.rxpermissions2.RxPermissions.io.reactivex.Observable request(io.reactivex.Observable,java.lang.String[])(RxPermissions.java:200)
14 com.tbruyelle.rxpermissions2.RxPermissions.com.tbruyelle.rxpermissions2.RxPermissionsFragment access$000(com.tbruyelle.rxpermissions2.RxPermissions,android.support.v4.app.FragmentManager)(RxPermissions.java:36)
15 ##_parent_##2##_parent_##
16 ##_child_## io.reactivex.Observable access$100(com.tbruyelle.rxpermissions2.RxPermissions,io.reactivex.Observable,java.lang.String[])##_child_##
17 ##_child_## io.reactivex.Observable access$200(com.tbruyelle.rxpermissions2.RxPermissions,java.lang.String[])##_child_##
18 com.tbruyelle.rxpermissions2.RxPermissions$2.io.reactivex.ObservableSource apply(io.reactivex.Observable)(RxPermissions.java:102)
19 io.reactivex.Observable.io.reactivex.Observable compose(io.reactivex.ObservableTransformer)(Observable.java:6284)
20 com.tbruyelle.rxpermissions2.RxPermissions.io.reactivex.Observable request(java.lang.String[])(RxPermissions.java:176)
21 com.xiaoyutimes.carloanonline.ui.main.query.value_query.query.ActivityValueQuery.void showChoosePicBottomSheetDialog()(ActivityValueQuery.java:819)
22 com.xiaoyutimes.carloanonline.ui.main.query.value_query.query.ActivityValueQuery.void onClick(android.view.View)(ActivityValueQuery.java:477)
23 com.xiaoyutimes.carloanonline.databinding.ViewIncludeValueQueryInfoBindingImpl.void _internalCallbackOnClick(int,android.view.View)(ViewIncludeValueQueryInfoBindingImpl.java:249)
24 com.xiaoyutimes.carloanonline.generated.callback.OnClickListener.void onClick(android.view.View)(OnClickListener.java:11)
25 android.view.View.performClick(View.java:5231)
26 android.view.View$PerformClick.run(View.java:21240)
27 android.os.Handler.handleCallback(Handler.java:739)
28 android.os.Handler.dispatchMessage(Handler.java:95)
29 android.os.Looper.loop(Looper.java:179)
30 android.app.ActivityThread.main(ActivityThread.java:5769)
31 java.lang.reflect.Method.invoke(Native Method)
32 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
33 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

`


![KVRMM5 $ 51AA (TW {YV~5](https://user-images.githubusercontent.com/20613737/55697388-da8b5480-59f3-11e9-8c4f-6caa26a0a993.png)

@mrArtCore  here u are
