### ISSUE TITLE
java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.

### ISSUE THREAD

**Issue by flztsj** [tbruyelle/RxPermissions#74] opened 2016-09-02 07:05 UTC
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: FATAL EXCEPTION: main
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: Process: xxx.xxxxxxxx.xxxxxxx.xxxxx, PID: 11720
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {xxx.xxxxxxxx.xxxxxxx.xxxxx/com.tbruyelle.rxpermissions.ShadowActivity}: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3929)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3972)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at android.app.ActivityThread.-wrap16(ActivityThread.java)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:111)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5728)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: Caused by: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at com.tbruyelle.rxpermissions.b.a(Unknown Source)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at com.tbruyelle.rxpermissions.ShadowActivity.onRequestPermissionsResult(Unknown Source)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6625)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6504)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3925)
08-31 14:08:34.464414 11720 11720 E AndroidRuntime: 	... 9 more

**Comment by tarasantoshchuk** [comment] 2016-09-03 08:10
duplicate of https://github.com/tbruyelle/RxPermissions/issues/46

**Closed** 2016-09-03 17:19 UTC
