### ISSUE TITLE
CRASH: Fold the app up when dialog is showing (dnka off)

### ISSUE THREAD

**Issue by artesa** [tbruyelle/RxPermissions#43] opened 2016-03-29 09:39 UTC
Hello,

Please note that the last version of the library (0.6.1) produces crash with the following steps (for the sample app):
0. "Do not keep activities" OFF
1. Open the sample app.
2. Press "Enable camera"
3. While the dialog is on the screen, fold the app up.
4. Retrieve the app from the recent apps.
5. Press "Allow".
Actual result: App crashes.

The log is as follows:
03-29 12:33:01.757 1921-1921/com.tbruyelle.rxpermissions.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.tbruyelle.rxpermissions.sample, PID: 1921
                                                                                  java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.tbruyelle.rxpermissions.sample/com.tbruyelle.rxpermissions.ShadowActivity}: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
                                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
                                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
                                                                                      at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                   Caused by: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
                                                                                      at com.tbruyelle.rxpermissions.RxPermissions.onRequestPermissionsResult(RxPermissions.java:302)
                                                                                      at com.tbruyelle.rxpermissions.ShadowActivity.onRequestPermissionsResult(ShadowActivity.java:32)
                                                                                      at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6582)
                                                                                      at android.app.Activity.dispatchActivityResult(Activity.java:6460)
                                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
                                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742) 
                                                                                      at android.app.ActivityThread.-wrap16(ActivityThread.java) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by tbruyelle** [comment] 2016-03-30 08:27
The crash was introduced with 88d83bb3c07f3bd1aaa6852ce37427c9928d9860 where I moved code from `onDestroy` to `onStop`.

Quick solution is to move the client code in `onStart` rather than `onCreate` but I dislike the idea. Too bad we can't rely on `onDestroy`, since this is the only method in the lifecycle where it is certain that `onCreate` will be invoked on back. With `onStop`, it can be `onCreate` or `onStart`, it depends... Android lifecycle is really a fucking disaster, so tired of fighting against it for years...

I try to find an other fix.

**Comment by artesa** [comment] 2016-03-30 12:11
Is it really important to do 
`        mSubjects.clear();`
in the `onShadowActivityStop()`? If the activity dies, this list will be just dropped with it, otherwise, if the activity survives and continues its lifecycle, we need this list untouched (bug is actually caused by its emptiness after onStop()).

I removed it and checked the main cases, everything works as expected.

**Comment by tbruyelle** [comment] 2016-03-30 12:27
Yes it's important for a feature that begin to annoy me : multiple request handling. 

But I'm going to take my axe, remove that feature and at the same time some complicated code. I don't think people use it. Even me I'm not using it any more.

**Comment by artesa** [comment] 2016-03-30 12:39
I am using it :) We are requesting android.permission.CAMERA and android.permission.RECORD_AUDIO at the same point.

Aha, I see - there is a case, when I request two permissions simultaneously, DNKA on, I press "Allow" on the first dialog, then fold the app up, retrieve it back, press "Allow" on the second dialog. Without this line of code, result would not be delivered.
In the current implementation of the library, however, it produces the same crash as in the description of the issue.

I'll look for some ways to handle it.

**Comment by tbruyelle** [comment] 2016-03-30 12:45
I'm not talking about multiple requests when you provide 2 or more parameters, I'm talking about multiple requests done at the same time for the same permission in 2 different places of your code. 
So, do you really use that feature ?

**Comment by artesa** [comment] 2016-03-30 12:47
That one no (and, honestly speaking, I can hardly imagine a case when it could be inevitably needed).

**Closed** 2016-03-30 12:56 UTC
Labels: bug

**Comment by tbruyelle** [comment] 2016-03-30 12:58
> I can hardly imagine a case when it could be inevitably needed

I agree, I was probably drunk when I decided to handle that.

I pushed some fix to master, could you check if it's ok (also if possible the last test you made about multiple permissions request ?) 

Thanks in advance!

**Comment by artesa** [comment] 2016-03-30 13:49
Checked - no crash now, with one permission it works as expected.

For two permissions, requested simultaneously, there is no more crash as well and all works good with DNKA off. With DNKA on, there stays the case when result is not delivered ("Allow" on the first dialog, fold up, retrieve, "Allow" on the second dialog). But I suppose it to be extremely rare, probably not worth wasting time.

Also checked the two previous cases - none reproduces.

That's great :)

Thank you very much for the fixes and quick reaction! You helped us a lot.

**Comment by tbruyelle** [comment] 2016-03-30 14:38
Good!

About the last issue, I tried to reproduce with sample app, by adding a second permission to the parameter list, with DNKA on, but it worked mostly as expected (mostly because the result was delivered 2 times instead of one to the subscriber, will see if I can improve that).

When you said *requested simultaneously* you mean by passing more than one parameter ?

**Comment by artesa** [comment] 2016-03-30 14:56
> When you said requested simultaneously you mean by passing more than one parameter ?
Yes. Maybe it's somehow device-specific, I'm testing on Nexus 5, 6.0.1.

Would you please deploy a new version of the library, for us to receive updates?

**Comment by tbruyelle** [comment] 2016-03-30 15:06
Done, new version is 0.7.0 since a *feature* has been removed.
