### ISSUE TITLE
IllegalStateException: FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by leodeleon22** [tbruyelle/RxPermissions#235] opened 2018-07-10 08:50 UTC
I'm targeting API 27 and using the 0.10.1 version of the library but I receive this crash when I check the permissions _onCreateView_ of a fragment I just added. Is there any workaround @epool ?

`java.lang.IllegalStateException: FragmentManager is already executing transactions
        at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2179)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2211)
        at android.support.v4.app.BackStackRecord.commitNow(BackStackRecord.java:643)
        at com.tbruyelle.rxpermissions2.RxPermissions.getRxPermissionsFragment(RxPermissions.java:71)
        at com.tbruyelle.rxpermissions2.RxPermissions.access$000(RxPermissions.java:34)
        at com.tbruyelle.rxpermissions2.RxPermissions$1.get(RxPermissions.java:54)
        at com.tbruyelle.rxpermissions2.RxPermissions$1.get(RxPermissions.java:47)
        at com.tbruyelle.rxpermissions2.RxPermissions.isGranted(RxPermissions.java:302)`

**Comment by tbruyelle** [comment] 2018-07-10 15:59
duplicate of #214

**Closed by tbruyelle** 2018-07-10 15:59 UTC
Labels: duplicate

**Comment by moz1q1** [comment] 2020-01-16 02:35
are you ok?
