### ISSUE TITLE
hello，You don't have to bring it RxJAVA

### ISSUE THREAD

**Issue by 317056658** [tbruyelle/RxPermissions#256] opened 2018-10-22 09:53 UTC
This library comes with RxJava2 can you import RxJava2 yourself?Remove the library itself?

**Comment by ewoks** [comment] 2018-11-13 13:43
@tbruyelle  this is another duplicate of #257 and it should be deleted.
@317056658 please do not add duplicate issues. That will just make maintainer jobs more difficult and solution will come later, if ever. Thanks

**Closed** 2018-11-19 08:56 UTC
